"""Dependency manifest checks.

AG009 (bundled vulnerability advisories) was removed in favour of delegating to
purpose-built tools. See docs/RULE_IDS.md for why, and for the guarantee that the
identifier will never be reused.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from agentguard.context import SourceFile
from agentguard.models import Finding, Severity
from agentguard.rules.base import Rule, RuleMetadata


class UnpinnedDependencyRule(Rule):
    metadata = RuleMetadata(
        "AG010",
        "Unpinned production dependency",
        Severity.LOW,
        "dependencies",
        "Detects reproducibility and supply-chain gaps.",
        languages=frozenset({"manifest"}),
    )

    def scan(self, source: SourceFile) -> Iterable[Finding]:
        if not (source.path.name.startswith("requirements") and source.path.suffix == ".txt"):
            return
        for number, line in enumerate(source.lines, 1):
            stripped = line.strip()
            if not stripped or stripped.startswith(("#", "-r", "--")):
                continue
            if re.match(r"[A-Za-z0-9_.-]+\s*$", stripped):
                yield self.finding(
                    source,
                    number,
                    f"Dependency `{stripped}` has no version constraint.",
                    "A compromised or incompatible future release can enter builds without review.",
                    "Use a lockfile or hash-pinned constraints generated by a trusted dependency workflow and enable automated update review.",
                )
